# Generated by Django 5.1.6 on 2025-02-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration of the subscription in months'),
            preserve_default=False,
        ),
    ]
