# Generated by Django 5.1.6 on 2025-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_remove_subscription_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='personal_training',
            field=models.BooleanField(default='False'),
        ),
    ]
