# Generated by Django 5.1.6 on 2025-02-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_subscription_personal_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='availability',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Both', 'Both')], default='Both', max_length=50),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='qualifications',
            field=models.TextField(default='BSC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
            preserve_default=False,
        ),
    ]
