# Generated by Django 5.1.6 on 2025-03-07 14:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_trainerprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.IntegerField(default=165, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('weight', models.IntegerField(default=65, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(1000)])),
                ('age', models.IntegerField(default=16)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='sedentary', max_length=15, verbose_name='Activity Level')),
                ('breakfast', models.JSONField(default=list)),
                ('morning_snack', models.JSONField(default=list)),
                ('lunch', models.JSONField(default=list)),
                ('evening_snack', models.JSONField(default=list)),
                ('dinner', models.JSONField(default=list)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
