# Generated by Django 5.1.6 on 2025-03-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_nutritiongoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiongoal',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
    ]
