# Generated by Django 5.1.6 on 2025-03-09 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_nutritiongoal_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultUserMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.IntegerField(default=165, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('weight', models.IntegerField(default=65, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(1000)])),
                ('age', models.IntegerField(default=16)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='sedentary', max_length=15, verbose_name='Activity Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
