# Generated by Django 5.1.6 on 2025-03-10 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_defaultusermetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritiongoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL),
        ),
    ]
