# Generated by Django 5.1.6 on 2025-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_nutritiongoal_unique_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritiongoal',
            name='created_at',
            field=models.DateField(),
        ),
    ]
