# Generated by Django 5.1.6 on 2025-03-10 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_alter_nutritiongoal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritiongoal',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
