# Generated by Django 5.1.6 on 2025-03-20 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_alter_nutritiongoal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('fortifit', 'Fortifit')], default='online', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'created_at')},
        ),
        
    ]
