# Generated by Django 5.1.6 on 2025-03-15 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0015_defaultworkout_trainerassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutday',
            name='workout_plan',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='user',
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise', to='gymapp.dailyworkout'),
        ),
        migrations.DeleteModel(
            name='WorkoutDay',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
