# Generated by Django 5.1.6 on 2025-03-15 05:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0016_remove_workoutday_workout_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='body_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_body_part', to='gymapp.bodypart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultworkout',
            name='body_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_body_part', to='gymapp.bodypart'),
            preserve_default=False,
        ),
    ]
