# Generated by Django 5.1.6 on 2025-03-15 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0017_bodypart_dailyworkout_body_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultworkout',
            name='reps',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='defaultworkout',
            name='rest',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='defaultworkout',
            name='sets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
