# Generated by Django 5.1.6 on 2025-03-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0018_defaultworkout_reps_defaultworkout_rest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultworkout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='defaultworkout',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='defaultworkout',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='sets',
        ),
    ]
