# Generated by Django 5.1.6 on 2025-03-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0019_remove_defaultworkout_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultworkout',
            name='reps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='defaultworkout',
            name='rest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='defaultworkout',
            name='sets',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='reps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='rest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='sets',
            field=models.JSONField(default=list),
        ),
    ]
