# Generated by Django 5.1.6 on 2025-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0020_defaultworkout_reps_defaultworkout_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultworkout',
            name='exercises',
            field=models.ManyToManyField(related_name='default_workouts', to='gymapp.exercise'),
        ),
    ]
