# Generated by Django 5.1.6 on 2025-03-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0021_alter_defaultworkout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultworkout',
            name='exercises',
            field=models.ManyToManyField(related_name='default_exercise', to='gymapp.exercise'),
        ),
    ]
