# Generated by Django 5.1.6 on 2025-03-15 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0022_alter_defaultworkout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='rest',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RemoveField(
            model_name='defaultworkout',
            name='exercises',
        ),
    ]
