# Generated by Django 5.1.6 on 2025-03-15 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0023_alter_workoutexercise_reps_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='defaultworkout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='defaultworkout',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='defaultworkout',
            name='sets',
        ),
        migrations.CreateModel(
            name='DefaultWorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('reps', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('rest', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_exercise_instance', to='gymapp.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_workout_exercise', to='gymapp.defaultworkout')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workout', 'exercise'), name='unique_default_workout_exercise')],
            },
        ),
    ]
