# Generated by Django 5.1.6 on 2025-03-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0024_remove_defaultworkout_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultworkoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='defaultworkoutexercise',
            name='workout',
        ),
        migrations.RemoveConstraint(
            model_name='defaultworkout',
            name='user_default_workout',
        ),
        migrations.RemoveField(
            model_name='defaultworkout',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='defaultworkout',
            name='day',
        ),
        migrations.AddField(
            model_name='defaultworkout',
            name='exercise_data',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='DefaultWorkoutExercise',
        ),
    ]
