# Generated by Django 5.1.6 on 2025-03-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0025_remove_defaultworkoutexercise_exercise_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='defaultworkout',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_default_workout'),
        ),
    ]
