# Generated by Django 5.1.6 on 2025-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0026_defaultworkout_unique_user_default_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyworkout',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='exercise_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='dailyworkout',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_exercise'),
        ),
        migrations.DeleteModel(
            name='BodyPart',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
