# Generated by Django 5.1.6 on 2025-03-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0016_chatmessage_trainerassignment'),
        ('gymapp', '0027_remove_dailyworkout_body_part_and_more'),
    ]

    operations = [
    ]
