# Generated by Django 5.1.6 on 2025-03-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0028_merge_20250323_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
    ]
