# Generated by Django 5.1.6 on 2025-03-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0029_remove_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
