# Generated by Django 5.1.6 on 2025-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0030_attendance_check_in_time_attendance_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
