# Generated by Django 5.1.6 on 2025-03-30 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0032_payment_razorpay_payment_link_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
